id: PADF677B3
initial_creation_type: input
source_metadata:
  Title: Mahayana sutralankara of Asanga with its Svavrtti
  Editor: Bagchi, S.
  Publisher: The Mithila Institute of Post-Graduate Studies and Research in Sanskrit
    Learning
  Place of Publication: Darbhanga
  Year: '1970'
  Prathamo'dhikāraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Dvitīyo'dhikāraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Tṛtīyo'dhikāraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Caturtho'dhikāraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Pañcamo'dhikāraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Ṣaṣṭho'dhikāraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Saptamo'dhikāraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Aṣṭamo'dhikāraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Navamo'dhikāraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Daśamodhikāraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Ekādaśo'dhikāraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Dvādaśo'dhikāraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Trayodaśo'dhikāraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Caturdaśo'dhikāraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Pañcadaśo'dhikāraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Ṣoḍaśo'dhikāraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Saptadaśo'dhikāraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Aṣṭādaśo'dhikāraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Ekonaviṃśatyadhikāraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Viṃśatitamaekaviṃśatitamaścādhikāraḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:55:31.532654'
last_modified_at: '2022-03-08T16:55:31.532667'
